Update Ci.yml

diff --git a/.github/workflows/Ci.yml b/.github/workflows/Ci.yml
--- a/.github/workflows/Ci.yml
+++ b/.github/workflows/Ci.yml
@@ -25,16 +25,23 @@ jobs:
 
     - name: Run MLflow Project
       run: |
-        # Menggunakan local environment agar tidak mencari pyenv
         mlflow run ./MLProject --env-manager=local
 
     - name: Build Docker Image
       run: |
-        MODEL_PATH=$(find MLProject/mlruns -name "model" -type d | head -n 1)
-          echo "Model ditemukan di: $MODEL_PATH"
-        
+        RUN_ID=$(ls -t MLProject/mlruns/0 | grep -v "meta.yaml" | head -n 1)
+        echo "Run ID Ditemukan: $RUN_ID"
+
+        MODEL_SUBFOLDER=$(find MLProject/mlruns/0/$RUN_ID/models -name "m-*" -type d | head -n 1)
+        echo "Path Model: $MODEL_SUBFOLDER"
+
+        if [ ! -f "$MODEL_SUBFOLDER/MLmodel" ]; then
+          echo "Error: File MLmodel tidak ditemukan di $MODEL_SUBFOLDER"
+          exit 1
+        fi
+
         mlflow models build-docker \
-          -m "runs:/$LAST_RUN_ID/model" \
+          -m "$MODEL_SUBFOLDER" \
           -n ${{ secrets.DOCKER_USERNAME }}/mlflow-workflow-ci \
           --env-manager=local
 
